# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/khayu43/Documents/Python/drag_drop/graph_csv_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(662, 784)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 10, 641, 711))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.FileButton = QtWidgets.QPushButton(self.widget)
        self.FileButton.setObjectName("FileButton")
        self.gridLayout.addWidget(self.FileButton, 0, 0, 1, 1)
        self.XLable = QtWidgets.QLabel(self.widget)
        self.XLable.setAlignment(QtCore.Qt.AlignCenter)
        self.XLable.setObjectName("XLable")
        self.gridLayout.addWidget(self.XLable, 1, 0, 1, 1)
        self.comboBox_1 = QtWidgets.QComboBox(self.widget)
        self.comboBox_1.setObjectName("comboBox_1")
        self.gridLayout.addWidget(self.comboBox_1, 1, 1, 1, 1)
        self.YLable = QtWidgets.QLabel(self.widget)
        self.YLable.setAlignment(QtCore.Qt.AlignCenter)
        self.YLable.setObjectName("YLable")
        self.gridLayout.addWidget(self.YLable, 2, 0, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.widget)
        self.comboBox_2.setObjectName("comboBox_2")
        self.gridLayout.addWidget(self.comboBox_2, 2, 1, 1, 1)
        self.horizontalLayout_1 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_1.setObjectName("horizontalLayout_1")
        self.PlotButton = QtWidgets.QPushButton(self.widget)
        self.PlotButton.setObjectName("PlotButton")
        self.horizontalLayout_1.addWidget(self.PlotButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_1.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout_1, 3, 0, 1, 2)
        self.verticalLayout1 = QtWidgets.QVBoxLayout()
        self.verticalLayout1.setObjectName("verticalLayout1")
        spacerItem1 = QtWidgets.QSpacerItem(5, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout1.addItem(spacerItem1)
        self.gridLayout.addLayout(self.verticalLayout1, 4, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 662, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setCheckable(False)
        self.actionClose.setObjectName("actionClose")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.FileButton.setText(_translate("MainWindow", "Open"))
        self.XLable.setText(_translate("MainWindow", "X axis column"))
        self.YLable.setText(_translate("MainWindow", "Y axis column"))
        self.PlotButton.setText(_translate("MainWindow", "Plot"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
